ARG VERSION
FROM almalinux:${VERSION:-9}

# docker build -t arg:v1 --build-arg VERSION=8 .
# if we give aurument then arugment will applies to almalinux os like example if we give VERSION=8 then base os will 8 verison other wise 9 version
